Product:
    type: object
    config:
        description: "Product Type"
        fields:
            id:
                type: "Int"
                description: "Product ID"
            title:
                type: "String"
                description: "Product Name"
            key:
                type: "String"
                description: "Product Code"