ProductInput:
    type: input-object
    config:
        fields:
            name:
                type: "String"
                description: "Name Product"
            quantity:
                type: "Int"
                description: "Price Quantity"
            price:
                type: "Float"
                description: "Price Product"