Product:
    type: object
    config:
        description: "Product Type"
        fields:
            id:
                type: "Int"
                description: "Product ID"
            name:
                type: "String"
                description: "Product Name"
            quantity:
                type: "Int"
                description: "Product Quantity"
            price:
                type: "Float"
                description: "Product Price"