Query:
    type: object
    config:
        description: "Main Query"
        fields:
            product:
                type: "Product"
                args:
                    id:
                        description: "Get product by ID"
                        type: "Int"
                resolve: "@=resolver('Product', [args])"
            products_collection:
                type: "ProductCollection"
                args:
                    limit:
                        description: "Limit query"
                        type: "Int"
                resolve: "@=resolver('ProductCollection', [args])"